[package]
name = "contract_ref"
<<<<<<< HEAD
version = "5.0.0"
=======
version = "5.0.0-rc.3"
>>>>>>> master
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }

integration_flipper = { path = "../integration-flipper", default-features = false, features = ["ink-as-dependency"] }

[dev-dependencies]
ink_e2e = { path = "../../../crates/e2e" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",

    "integration_flipper/std",
]
ink-as-dependency = []
e2e-tests = []
