version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "sp-*"
        update-types: ["minor", "patch"]
      - dependency-name: "pallet-*"
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
