version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # ignore Substrate pallets major updates.
    # automated Substrate releases cause dependabot PR spam, so these must be updated manually when required.
    ignore:
      - dependency-name: "sp-*"
        update-types: ["major"]
      - dependency-name: "pallet-*"
        update-types: ["major"]
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
