version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - ignore:
      - dependency-name: sp-core
      - dependency-name: sp-keyring
      - dependency-name: sp-runtime
      - dependency-name: sp-weights
      - dependency-name: pallet-contracts-primitives
