[package]
name = "ink_env"
version = "4.0.0-alpha.3"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_env/"
homepage = "https://www.parity.io/"
description = "[ink!] Low-level interface for interacting with the smart contract Wasm executor."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_metadata = { version = "4.0.0-alpha.3", path = "../metadata", default-features = false, features = ["derive"], optional = true }
ink_allocator = { version = "4.0.0-alpha.3", path = "../allocator", default-features = false }
ink_storage_traits = { version = "4.0.0-alpha.3", path = "../storage/traits", default-features = false }
ink_prelude = { version = "4.0.0-alpha.3", path = "../prelude", default-features = false }
ink_primitives = { version = "4.0.0-alpha.3", path = "../primitives", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
derive_more = { version = "0.99", default-features = false, features = ["from", "display"] }
num-traits = { version = "0.2", default-features = false, features = ["i128"] }
cfg-if = "1.0"
paste = "1.0"
arrayref = "0.3"
static_assertions = "1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rlibc = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ink_engine = { version = "4.0.0-alpha.3", path = "../engine/", optional = true }

# Hashes for the off-chain environment.
sha2 = { version = "0.10", optional = true }
sha3 = { version = "0.10", optional = true }
blake2 = { version = "0.10", optional = true }

# ECDSA for the off-chain environment.
secp256k1 = { version = "0.24", features = ["recovery", "global-context"], optional = true }

# Only used in the off-chain environment.
#
# Sadly couldn't be marked as dev-dependency.
# Never use this crate outside the off-chain environment!
rand = { version = "0.8", default-features = false, features = ["alloc"], optional = true }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

contract-metadata = { version = "2.0.0-alpha.2", optional = true }
impl-serde = { version = "0.3.1", default-features = false, optional = true  }
jsonrpsee = { version = "0.14.0", features = ["ws-client"], optional = true  }
pallet-contracts-primitives = { version = "6.0.0", optional = true }
serde = { version = "1.0.137", default-features = false, features = ["derive"], optional = true }
serde_json = { version = "1.0.81", optional = true }
tokio = { version = "1.18.2", features = ["rt-multi-thread"], optional = true }
log = { version = "0.4", optional = true }
env_logger = { version = "0.9", optional = true }
subxt = { version = "0.24.0", optional = true }

# Substrate
sp-rpc = { version = "6.0.0", optional = true }
sp-core = { version = "6.0.0", optional = true }
sp-keyring = { version = "6.0.0", optional = true }
sp-runtime = { version = "6.0.0", optional = true }

# TODO(#1421) `smart-bench_macro` needs to be forked.
smart-bench-macro = { git = "https://github.com/paritytech/smart-bench", branch = "cmichi-ink-e2e-test-mvp", package = "smart-bench-macro", optional = true}

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_allocator/std",
    "ink_prelude/std",
    "ink_primitives/std",
    "ink_storage_traits/std",
    "ink_engine/std",
    "scale/std",
    "scale-info/std",
    "secp256k1",
    "rand/std",
    "rand/std_rng",
    "num-traits/std",
    # Enables hashing crates for off-chain environment.
    "sha2",
    "sha3",
    "blake2",
    # E2E testing environment
    "contract-metadata",
    "impl-serde",
    "jsonrpsee",
    "pallet-contracts-primitives",
    "serde",
    "serde_json",
    "tokio",
    "log",
    "env_logger",
    "subxt",
    "sp-rpc",
    "sp-core",
    "sp-keyring",
    "sp-runtime",
    "smart-bench-macro",
]
# Enable contract debug messages via `debug_print!` and `debug_println!`.
ink-debug = []
