[package]
name = "ink_ir"
version.workspace = true
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_ir/"
homepage.workspace = true
description = "data structures and algorithms for ink! intermediate representation"
keywords.workspace = true
categories.workspace = true
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[lib]
name = "ink_ir"

[dependencies]
quote = { workspace = true }
syn = { workspace = true, features = ["parsing", "full", "visit", "extra-traits"] }
proc-macro2 = { workspace = true }
itertools = { workspace = true }
either = { workspace = true }
blake2 = { workspace = true }
ink_prelude = { workspace = true }

[features]
default = ["std"]
std = [
    "itertools/use_std",
    "either/use_std",
]
