[package]
name = "contract-xcm"
version = "4.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = false

[dependencies]
ink = { path = "../../crates/ink", default-features = false }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", rev = "59f868d1e9502cb4e434127cac6e439d01d7dd2b", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk", rev = "59f868d1e9502cb4e434127cac6e439d01d7dd2b", default-features = false }

# Substrate
#
# We need to explicitly turn off some of the `sp-io` features, to avoid conflicts
# (especially for global allocator).
#
# See also: https://substrate.stackexchange.com/questions/4733/error-when-compiling-a-contract-using-the-xcm-chain-extension.
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", rev = "59f868d1e9502cb4e434127cac6e439d01d7dd2b", default-features = false, features = ["disable_panic_handler", "disable_oom", "disable_allocator"] }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", rev = "59f868d1e9502cb4e434127cac6e439d01d7dd2b", default-features = false }

[dev-dependencies]
ink_e2e = { path = "../../crates/e2e", features = ["sandbox"] }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "sp-runtime/std",
    "sp-io/std",
    "pallet-balances/std",
    "frame-support/std",
]
ink-as-dependency = []
e2e-tests = []
