[workspace]
resolver = "2"
members = [
    "mandatory",
    "extra",
    "utils",
]

[workspace.package]
<<<<<<< HEAD
version = "5.0.0"
=======
version = "5.0.0-rc.3"
>>>>>>> master
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/paritytech/ink"
homepage = "https://www.parity.io/"
keywords = ["parity", "blockchain", "edsl", "dylint", "linting"]

[workspace.dependencies]
<<<<<<< HEAD
ink_linting_utils = { version = "=5.0.0", path = "utils" }
=======
ink_linting_utils = { version = "=5.0.0-rc.3", path = "utils" }
>>>>>>> master
curve25519-dalek = { version = "=4.1.1", default-features = false, features = [
    "digest",
    "zeroize",
    "precomputed-tables",
    "legacy_compatibility",
] }
[workspace.metadata.dylint]
libraries = [
    { path = "mandatory" },
    { path = "extra" },
]
