[package]
name = "ink_primitives"
version.workspace = true
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_primitives/"
homepage.workspace = true
description = "[ink!] Fundamental primitive types for ink! smart contracts."
keywords.workspace = true
categories.workspace = true
include = ["/Cargo.toml", "src/**/*.rs", "/README.md", "/LICENSE"]

[dependencies]
derive_more = { workspace = true, features = ["from", "display"] }
ink_prelude = { workspace = true }
scale = { package = "parity-scale-codec", workspace = true }
scale-decode = { workspace = true, features = ["derive"], optional = true }
scale-encode = { workspace = true, features = ["derive"], optional = true }
scale-info = { workspace = true, features = ["derive"], optional = true }
xxhash-rust = { workspace = true, features = ["const_xxh32"] }
cfg-if = { workspace = true }
num-traits = { workspace = true, features = ["i128"] }

[dev-dependencies]
ink = { workspace = true, default-features = false }
ink_env = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
    "ink/std",
    "ink_env/std",
    "ink_prelude/std",
    "scale/std",
    "scale-decode",
    "scale-encode",
    "scale-info/std",
]
