name: continuous-intergration/macos

on:
  push:
    branches:
      - master
    tags:
        - v*
    paths-ignore:
      - 'README.md'
      - '.gitlab-ci.yml'

jobs:
  check:
    name: build-examples
    strategy:
      matrix:
        platform:
          - macos-latest
        toolchain:
          - nightly
    runs-on: ${{ matrix.platform }}
    env:
      RUST_BACKTRACE: full
      DELEGATOR_SUBCONTRACTS: "accumulator adder subber"
    steps:

      - uses: actions/setup-node@v2
      - run: npm install wasm-opt -g

      - name: Checkout sources & submodules
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: rust-src
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.2.0

      - name: Install `cargo-contract` `master`
        uses: actions-rs/cargo@v1
        with:
            command: install
            args: --git https://github.com/paritytech/cargo-contract.git

      - name: Output versions
        run: |
            wasm-opt --version
            cargo -vV
            cargo contract --version

      - name: Build examples on ${{ matrix.platform }}-${{ matrix.toolchain }}
        run: |
          for example in examples/*/; do
              echo "Building example: $example";
              cargo contract build --manifest-path=$example/Cargo.toml;
          done
          cd examples/delegator/ && ./build-all.sh

      - name: Test examples on ${{ matrix.platform }}-${{ matrix.toolchain }}
        run: |
            for example in examples/*/; do
                echo "Testing example: $example";
                cargo test --verbose --manifest-path=$example/Cargo.toml;
            done
            for contract in ${DELEGATOR_SUBCONTRACTS}; do
                echo "Testing delegator contract: $contract";
                cargo test --verbose --manifest-path examples/delegator/${contract}/Cargo.toml;
            done
