name: continuous-intergration/measurements

on:
  workflow_call:

env:
  CARGO_TARGET_DIR:                /ci-cache/${{ github.repository }}/targets/${{ github.ref_name }}/${{ github.job }}

jobs:
  contract-sizes:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: paritytech/ci-unified:bullseye-1.75.0
    strategy:
      fail-fast: false
      matrix:
        branch: [master, pull_request]
    steps:
      - name: Checkout Master
        if: ${{ matrix.branch == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout Pull Request
        if: ${{ matrix.branch == 'master' }}
        uses: actions/checkout@v4
        with:
          branch: master
          fetch-depth: 1

      - name: Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-directories: ${{ env.CARGO_TARGET_DIR }}

      - name: Rust Info
        uses: ./.github/rust-info

      - name: Measure Contract Sizes
        env:
          PR_NUMBER:                ${{ github.event.number }}
        run: |
          # Variables
          MEASUREMENTS_DIR="${GITHUB_WORKSPACE}/measurements"
          SCRIPTS_DIR="${GITHUB_WORKSPACE}/scripts"
          CONTRACT_SIZES="${MEASUREMENTS_DIR}/${{ matrix.branch }}_contract_sizes"

          # Measure contract sizes for the current branch
          mkdir ${MEASUREMENTS_DIR}
          ${SCRIPTS_DIR}/for_all_contracts_exec.sh --path integration-tests --quiet -- ${SCRIPTS_DIR}/contract_size.sh {} > ${CONTRACT_SIZES}
          sed -i '' 's/^integration-tests\///g' ${CONTRACT_SIZES}

          CARGO_CONTRACT_VERSION=$(cargo-contract --version | egrep --only-matching "cargo-contract.* .*-x86" | sed -s 's/-x86//')
          echo "CARGO_CONTRACT_VERSION=\"${CARGO_CONTRACT_VERSION}\"" > ${MEASUREMENTS_DIR}/context.out
          echo "PR_NUMBER=\"${PR_NUMBER}\"" >> ${MEASUREMENTS_DIR}/context.out

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-${{ matrix.branch }}-data
          path: ./measurements
          retention-days: 1

  # test job only
  submit-contract-sizes:
    runs-on: ubuntu-latest
    needs: [contract-sizes]
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download Contract Sizes
        uses: ./.github/download-artifact
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_NAME: contract-sizes-master-data

      - name: Download Contract Sizes
        uses: ./.github/download-artifact
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_NAME: contract-sizes-pull_request-data

      - name: Collect Contract Sizes
        env:
          PR_NUMBER:               ${{ github.event.workflow_run.event.number }}
        run: |
          # Variables
          SCRIPTS_DIR="${GITHUB_WORKSPACE}/scripts"
          PR_CONTRACT_SIZES="pull_request_contract_sizes"
          UPSTREAM_CONTRACT_SIZES="master_contract_sizes"

          # Build the comparison table
          ${SCRIPTS_DIR}/contract_sizes_diff.sh ${UPSTREAM_CONTRACT_SIZES} ${PR_CONTRACT_SIZES} > contract_sizes_diff.md
          cat ${CONTRACT_SIZES_DIFF}
          CARGO_CONTRACT_VERSION=$(cargo-contract --version | egrep --only-matching "cargo-contract.* .*-x86" | sed -s 's/-x86//')

      - name: Submit Comment
        env:
          GITHUB_PR_TOKEN:         ${{ secrets.github_token }}
          GITHUB_PR_WORKFLOW_ID:   ${{ github.event.workflow_run.id }}
        run: |
          SCRIPTS_DIR="${GITHUB_WORKSPACE}/scripts"
          # context.out is considered as an untrusted file
          PR_NUMBER=$(grep -oE 'PR_NUMBER="[^"]+"' context.out | awk -F '"' '{print $2}')
          CARGO_CONTRACT_VERSION=$(grep -oE 'CARGO_CONTRACT_VERSION="[^"]+"' context.out | awk -F '"' '{print $2}')
          PR_COMMENTS_URL="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments"
          WORKFLOW_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_PR_WORKFLOW_ID}"

          # Submit the comparison table as a comment to the PR
          echo "Submitting contract sizes diff to ${PR_COMMENTS_URL}"
          GITHUB_PR_TOKEN=${GITHUB_PR_TOKEN} ${SCRIPTS_DIR}/contract_sizes_submit.sh ${PR_COMMENTS_URL} ${WORKFLOW_URL} ${CARGO_CONTRACT_VERSION} < ./contract_sizes_diff.md

