name: continuous-intergration/windows

on:
  push:
    branches:
      - master
    tags:
        - v*
    paths-ignore:
      - 'README.md'
      - '.gitlab-ci.yml'

jobs:
  check:
    name: build-examples
    strategy:
      matrix:
        platform:
          - windows-latest
        toolchain:
          - nightly
    runs-on: ${{ matrix.platform }}
    env:
      RUST_BACKTRACE: full
    steps:

      - uses: engineerd/configurator@v0.0.6
        with:
          name: "wasm-opt.exe"
          url: "https://github.com/WebAssembly/binaryen/releases/download/version_103/binaryen-version_103-x86_64-windows.tar.gz"
          pathInArchive: "binaryen-/bin/wasm-opt.exe"

      - name: Checkout sources & submodules
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: rust-src
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.2.0

      - name: Install `cargo-contract` `master`
        uses: actions-rs/cargo@v1
        with:
            command: install
            args: --git https://github.com/paritytech/cargo-contract.git

      - name: Output versions
        run: |
            wasm-opt --version
            cargo -vV
            cargo contract --version

      - name: Test examples on ${{ matrix.platform }}-${{ matrix.toolchain }}
        run: |
            $delegator_subcontracts = "accumulator","adder","subber"
            foreach ($contract in $delegator_subcontracts) {
                echo "Testing delegator contract: $contract";
                cargo test --verbose --manifest-path examples/delegator/${contract}/Cargo.toml;
            }
            foreach ($example in Get-ChildItem  -Directory "examples\*") {
                echo "Testing example: $example";
                cargo test --verbose --manifest-path=$example/Cargo.toml;
            }

      - name: Build examples on ${{ matrix.platform }}-${{ matrix.toolchain }}
        run: |
          foreach ($example in Get-ChildItem  -Directory "examples\*") {
              echo "Building example: $example";
              cargo contract build --manifest-path=$example/Cargo.toml;
          }
          cd examples/delegator/ && ./build-all.sh
